### ISSUE TITLE
Expose io from the plugin, so other parts of the code can use it

### ISSUE THREAD

**Issue by leobudima** [MCProHosting/wsabi#1]
Hi,

firstly, your plugin was a godsend - I'm migrating a Sails app to Hapi as well and the plugin really shed some light in how to approach the whole socket->route problem and saved me some time - so thank you for sharing it!

I was wondering if you would consider adding a simple line in _register_ method in _wsabi.js_ so it exposes _io_ to the rest of Hapi? 

`server.expose('io', io);`

It would then be accessible as:

`var io = server.plugins['wsabi'].io;`

I would, for example, use it to send events from models to subscribed sockets. If it's easier, I'd be happy to submit a PR. 

Thank you very much!

**Comment by connor4312** [comment]
Glad it's working for you! I added this in https://github.com/MCProHosting/wsabi/commit/d0ebb27277292525e775db56dad17ddcbc95536f and it's available in the 2.0.0 release. Let me know if you have any issues with it.

**Comment by leobudima** [comment]
@connor4312 - awesome - a big thanks for your response and help!
